### ISSUE TITLE
Redmine 4.2 compatibility

### ISSUE THREAD

**Issue by fwolfst** [speedy32129/time_logger#68]
Currently is not compatible with 4.2 (even with patch from #67).
The error thrown is super weird:
```
App 10224 output: Completed 500 Internal Server Error in 226ms (ActiveRecord: 106.6ms)
App 10224 output:   
App 10224 output: ArgumentError (wrong number of arguments (given 2, expected 0..1)):
App 10224 output:   
App 10224 output: plugins/time_logger/app/models/time_logger.rb:15:in `initialize'
App 10224 output: plugins/time_logger/app/controllers/time_loggers_controller.rb:18:in `start'
```

If somebody solves that riddle, I am curious to read the solution.

**Comment by fwolfst** [comment]
Just for fun, here the code references: :confused: 
https://github.com/speedy32129/time_logger/blob/6ecf2f59b095b7a7d19cb2a94f1c308debd5fefb/app/controllers/time_loggers_controller.rb#L18
https://github.com/speedy32129/time_logger/blob/6ecf2f59b095b7a7d19cb2a94f1c308debd5fefb/app/models/time_logger.rb#L15

**Comment by fwolfst** [comment]
Okay, solved in https://github.com/speedy32129/time_logger/issues/65#issuecomment-757379838 .

Still, I dont really get it. I had also modified the code to define an empty `initialize` and pass no arguments in the controller.
